### ISSUE TITLE
Game doesn't like lightning

### ISSUE THREAD

**Issue by Arthur-The-Ok** [FlinTyX/DiverseTech#6]
It was starting to rain, then a flash of light comes on and the game crashes.
This was the crash log:

rhino.EcmaError: TypeError: Cannot find function generateThunder in object diversetech-storm. (DTweathers#81)
	at rhino.ScriptRuntime.constructError(ScriptRuntime.java:3741)
	at rhino.ScriptRuntime.constructError(ScriptRuntime.java:3721)
	at rhino.ScriptRuntime.typeError(ScriptRuntime.java:3750)
	at rhino.ScriptRuntime.typeError2(ScriptRuntime.java:3766)
	at rhino.ScriptRuntime.notFunctionError(ScriptRuntime.java:3829)
	at rhino.ScriptRuntime.getPropFunctionAndThisHelper(ScriptRuntime.java:2192)
	at rhino.ScriptRuntime.getPropFunctionAndThis(ScriptRuntime.java:2175)
	at rhino.gen.DTweathers_100._c_anonymous_6(DTweathers:81)
	at rhino.gen.DTweathers_100.call(DTweathers)
	at rhino.ContextFactory.doTopCall(ContextFactory.java:328)
	at rhino.ScriptRuntime.doTopCall(ScriptRuntime.java:3114)
	at rhino.gen.DTweathers_100.call(DTweathers)
	at rhino.JavaAdapter.doCall(JavaAdapter.java:489)
	at rhino.JavaAdapter.callMethod(JavaAdapter.java:471)
	at adapter98.drawOver(<adapter>)
	at mindustry.gen.WeatherState.lambda$draw$0(WeatherState.java:440)
	at arc.graphics.g2d.SortedSpriteBatch.flushRequests(SortedSpriteBatch.java:117)
	at arc.graphics.g2d.SortedSpriteBatch.flush(SortedSpriteBatch.java:97)
	at arc.graphics.g2d.Draw.flush(Draw.java:352)
	at mindustry.core.Renderer.draw(Renderer.java:323)
	at mindustry.core.Renderer.update(Renderer.java:183)
	at arc.ApplicationCore.update(ApplicationCore.java:37)
	at mindustry.ClientLauncher.update(ClientLauncher.java:177)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:166)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:154)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:45)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:39)

**Comment by FlinTyX** [comment]
Thank you for opening this issue. The problem is fixed.
